{
  imports = [
    ./automount.nix
    ./bluetooth.nix
    ./bootloader.nix
    ./fonts.nix
    ./identity.nix
    ./keyboard.nix
    ./networking.nix
    ./polkit.nix
    ./privacy.nix
    ./sddm.nix
    ./sound.nix
    ./stylix.nix
    ./timezone.nix
    ./users.nix
    ./mimeapps.nix
    ./zapret.nix
  ];
}
